name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      worker_version_id: ${{ steps.get_version.outputs.worker_version_id }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: just build
      - name: Upload worker version
        id: upload
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.72.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCT_NUM }}
          command: versions upload
          workingDirectory: ./sh
      - name: Extract version id
        id: get_version
        run: |
          VERSION_ID=$(echo '${{ steps.upload.outputs.command-output }}' | grep "Worker Version ID" | awk '{print $4}')
          echo "worker_version_id=$VERSION_ID" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: just test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          rust-toolchain: nightly
          rust-components: rustfmt
      - run: just fmt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: just lint

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm i -g @lhci/cli@0.15.1
      - run: npm run build
        working-directory: ./site
      - run: lhci autorun
        working-directory: ./site
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - fmt
      - lint
      - lighthouse
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.72.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCT_NUM }}
          command: |
            versions deploy \
              --version-id ${{ needs.build.outputs.worker_version_id }} \
              --percentage 100 \
              --yes
          workingDirectory: ./sh
