name: CI

on:
  push:
  pull_request:

jobs:

  # Rust-based utils jobs

  build-utils:
    name: Build (utils)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - run: cargo build --release --locked --verbose


  test-utils:
    name: Test (utils)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - run: cargo test --release --locked --verbose


  lint-utils:
    name: Lint & Format (utils)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: nightly
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Lint with clippy
        run: cargo clippy -- -D warnings

  # Astro/npm site jobs

  build-site:
    name: Build (site)
    defaults:
      run:
        working-directory: ./site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install dh-sh
        run: cargo install --path utils/dh-sh
        working-directory: .
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build with Astro
        run: npm run build

  lint-site:
    name: Lint & Format (site)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run `biome ci`
        run: npm run biome ci

  test-site:
    name: Test (site)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test run

  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: site/package-lock.json
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.15.1
          lhci autorun
